OddpubMetrics Docker image and Database Table Generation
nimh-dsst/dsst-etl pull request #15
Opened 2024-12-11 08:20 UTC by quang-ng

Working on issue #14

2024-12-13 15:38 UTC, joshlawrimore commented
@leej3 can you test if the docker image installs oddpub in R in on your machine or @quang-ng can you write a GitHub action that tests it? I cannot build the latest image without the install of oddpub failing on my machine. Thanks!

2024-12-18 09:49 UTC, quang-ng commented
> @leej3 can you test if the docker image installs oddpub in R in on your machine or @quang-ng can you write a GitHub action that tests it? I cannot build the latest image without the install of oddpub failing on my machine. Thanks!

done, please help me review it

2024-12-18 17:13 UTC, leej3 requested changes
Thanks @quang-ng, it looks pretty solid! Some details to address but it's almost ready.

2024-12-18 17:13 UTC, leej3 commented on .docker/postgres-compose.yaml
> +  postgres-dsst:
What is this for? Would it be better to add a name to the compose file?
```
name: dsst
```

This will prepend the container name with dsst_ (by default the directory name is used). Is that sufficient namespacing or were you hitting some other issue?

2024-12-18 17:13 UTC, leej3 commented on services/oddpub/README.md
> +   poetry install
this should be conda right? Poetry won't satisfy dependencies for the service outside of the container?

2024-12-18 17:13 UTC, leej3 commented on services/oddpub/README.md
> +   uvicorn main:app --reload
can we use `fastapi run main.py` or something like that? unicorn seems like overkill here and might make debugging harder. Unless I am missing something...
If it supports higher throughput of pdfs then that's fine we can keep it.

2024-12-18 17:13 UTC, leej3 commented on services/oddpub/README.md
> +- Access the API at `http://localhost:8000/oddpub` to upload a PDF file and receive JSON output.
check port number in docs and app and testing. It might be good to keep consistent.

2024-12-18 17:13 UTC, leej3 commented on services/oddpub/_entrypoint.sh
> +exec "$@"
nice

2024-12-18 17:13 UTC, leej3 commented on services/oddpub/dockerfile
> +devtools::install_github("serghiou/rtransparent", build_vignettes = F)'
this isn't needed

2024-12-18 17:13 UTC, leej3 commented on services/oddpub/dockerfile
> +# Install pdftotext
move this earlier in the docker file (line 5)

2024-12-18 17:13 UTC, leej3 commented on services/oddpub/environment.yaml
> +  - r-crul
we don't need all these. I'll push a reduced set

2024-12-18 17:13 UTC, leej3 commented on services/oddpub/README.md
> +   docker run -p 80:80 oddpub-api
see above note on ports

2024-12-18 17:13 UTC, leej3 commented on .docker/postgres-compose.yaml
> +  oddpub-dsst:
if we add all the services to this file then we should move it to the root directory and rename it to compose.yaml.
We could also launch the container using python-on-whales, or add separate compose files to this directory.

2024-12-18 17:13 UTC, leej3 commented on services/oddpub/README.md
> +This is a FastAPI application for processing PDF files using the oddpub functions: `pdf_convert`, `pdf_load`, and `open_data_search`.
the entrypoint scripts would likely be more useful in the readme. I'm not convinced a readme is required here though. If the compose stack is the primary way to use this functionality it might be better to simply list a couple of commands that are useful for debugging (installing and running the server outside of a container perhaps)

2024-12-18 17:13 UTC, leej3 commented on .mockenv
> +ODDPUB_HOST_API=http://localhost:80
This should be 8071

2024-12-18 17:13 UTC, leej3 commented on dsst_etl/oddpub_wrapper.py
> +                    self.db_session.commit()
Can you provide some output to the user here to confirm the tool has run correctly and perhaps show the results concisely

2024-12-18 17:13 UTC, leej3 commented on dsst_etl/oddpub_wrapper.py
> +                    self.db_session.commit()
also, perhaps we should get user confirmation before uploading/updating the database and  have a -y flag for those who are sure they want to upload?

2024-12-18 17:13 UTC, leej3 commented on tests/test_oddpub.py
> +        inspector = inspect(self.engine)
why are we deleting here instead of rolling back?

2024-12-19 07:44 UTC, quang-ng commented on .docker/postgres-compose.yaml
> +  postgres-dsst:
No, no issue here, just change the name to more clear.

2024-12-19 07:49 UTC, quang-ng commented on services/oddpub/README.md
> +   poetry install
yes, I think we only run in container

2024-12-19 07:58 UTC, quang-ng commented on services/oddpub/README.md
> +   uvicorn main:app --reload
yes, I'm using `fastapi dev`, README.md is not consistent.

2024-12-19 08:07 UTC, quang-ng commented on services/oddpub/environment.yaml
> +  - r-crul
thanks

2024-12-19 08:28 UTC, quang-ng commented on services/oddpub/README.md
> +This is a FastAPI application for processing PDF files using the oddpub functions: `pdf_convert`, `pdf_load`, and `open_data_search`.
Running services outside of a container can make installation quite challenging. In a container, however, you can easily debug by accessing the log files. I believe we should avoid installing it directly without using Docker.

2024-12-23 13:53 UTC, leej3 approved these changes
@joshlawrimore could you merge this if you are happy with it.

LGTM. Thanks @quang-ng!

2024-12-23 13:53 UTC, leej3 commented on services/oddpub/README.md
> +This project is licensed under the MIT License.
let's address this separately

2024-12-24 07:03 UTC, quang-ng commented
Thank you @leej3 👍

2025-01-03 18:00 UTC, merged

2025-01-03 18:17 UTC, joshlawrimore commented
I was able to:

1. Run the `docker compose -f .docker/postgres-compose.yaml up -d` command to build the postgres and  oddpub images/containers. NOTE: this is due to me adding the --platform linux/arm64 flagtag to the oddpub dockerfile. Otherwise the installation of R packages fails for my M3 chip.
2. I am working from NIH today, which has a SSL cert issue python sometimes. I needed to socket into the oddpub container and specify a CRAN mirror in R to download oddpub dependencies prior to the oddpub service working for me. Just writing this down for later testing.
3.  I was able to run the `alembic upgrade head` command to create the database.
4. I was able to run the `dsst_etl.upload_pdfs.upload_directory` command on a test s3 bucket and confirmed the prescence of the records in the postgresdb hosted in my local container.
5. I was able to confirm the writing of the oddpub metrics to the postgres database. The entries didn't have connections to documents, but I assume we will address that in a later PR.

Great work @quang-ng !