Add AWS RDS configuration with PostgreSQL instance, security group
nimh-dsst/dsst-etl pull request #17
Opened 2024-12-18 10:13 UTC by quang-ng

2025-01-09 17:44 UTC, leej3 requested changes

2025-01-09 17:44 UTC, leej3 commented on .github/workflows/terraform.yml
> +
Use OIDC here by adding this step:
```
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-role-shared
```

2025-01-09 17:44 UTC, leej3 commented on .github/workflows/terraform.yml
> +    branches:
change this to use manual dispatch. We may only deploy it once but we'll see how things go. No doubt we'll be running it a few times on this PR to make sure things are working well.

2025-01-09 17:44 UTC, leej3 commented on .github/workflows/terraform.yml
> +        working-directory: ./terraform/state
this should be the postgres directory. state, networking, and iam provider/role have already been set up.

2025-01-09 17:44 UTC, leej3 commented on .github/workflows/terraform.yml
> +        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/terraform-sharing-db'
remove this, so that manual dispatch will work.

2025-01-09 17:44 UTC, leej3 commented on terraform/modules/iam/policies/gha-policy.json
> +        "rds:CreateDBInstance",
we may have to modify the permissions here. Let me know if that is required.

2025-01-11 03:04 UTC, quang-ng commented on .github/workflows/terraform.yml
> +
Hello @leej3, where we store `AWS_ACCOUNT_ID` and `AWS_REGION ` value?

2025-01-20 09:59 UTC, leej3 approved these changes
Abandoning deployment using GitHub Actions for now. This is available on branch add-github-workflow-for-postgres-deployment

2025-01-20 09:59 UTC, merged